/**
 * Generated by Scrooge
 *   version: 3.20.0
 *   rev: 0805321d69745466806017e1167a5027cd298d66
 *   built at: 20150727-174320
 */
package org.pantsbuild.example.hello.welcome

object Welcome {

}

trait W

trait Welcome
  extends W
  with scala.Product2[String, Option[org.pantsbuild.example.hello.greet.GreetScala]]
  with java.io.Serializable
{
}
